// existing map logic retained plus manual wizard system
let map;let markers={};let currentTrailLayer=null;let activeFilter='active';let dashboardLoads=[];const locallyTransitioned=new Map();
let manualPanel=1;const wizardState={carrier_id:0,driver_id:0,stops:[]};

const truckIcon=L.icon({iconUrl:'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png',shadowUrl:'https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png',iconSize:[25,41],iconAnchor:[12,41],popupAnchor:[1,-34],shadowSize:[41,41]});
let localCarrierIndex=[];
function collectCarrierIndex(){localCarrierIndex=(dashboardLoads||[]).map(l=>({carrier_id:l.carrier_id||0,carrier_name:l.carrier_name||'',dot_number:l.dot_number||''})).filter(x=>x.carrier_name);} 
function renderCarrierTypeahead(q){const box=document.getElementById('carrier-results');if(!box)return;box.innerHTML='';if(q.length<2)return;const matches=localCarrierIndex.filter(c=>c.carrier_name.toLowerCase().includes(q.toLowerCase())).slice(0,8);matches.forEach(item=>{const row=document.createElement('button');row.type='button';row.className='carrier-result';row.textContent=`${item.carrier_name} ${item.dot_number?`(${item.dot_number})`:''}`;row.onclick=()=>{document.getElementById('carrier_id').value=String(item.carrier_id||0);document.getElementById('carrier_name').value=item.carrier_name;document.getElementById('dot_number').value=item.dot_number||'';box.innerHTML='';};box.appendChild(row);});}
function normalizePhone(v){return String(v||'').replace(/\D/g,'').slice(0,10);} 
function resetManualLoadForm(){
const form=document.getElementById('manual-load-form');if(!form)return;
form.reset();
wizardState.carrier_id=0;wizardState.driver_id=0;wizardState.stops=[];
['carrier_id','driver_id','selected_carrier_id','selected_driver_id'].forEach(id=>{const el=document.getElementById(id);if(el)el.value='0';});
['carrier_name','dot_number','driver_name','driver_phone','driver_email','load_number'].forEach(id=>{const el=document.getElementById(id);if(el)el.value='';});
const stopsWrap=document.getElementById('stops-wrap');if(stopsWrap){stopsWrap.innerHTML='';addStopRow({milestone:'pickup'});addStopRow({milestone:'delivery'});} 
const results=document.getElementById('carrier-results');if(results)results.innerHTML='';
const sel=document.getElementById('driver_select');if(sel){sel.value='0';['driver_name','driver_phone','driver_email'].forEach(id=>{const lbl=document.getElementById(id)?.closest('label');if(lbl)lbl.style.display='block';});}
err('');showPanel(1);
}
function initMap(){map=L.map('map').setView([43,-93.5],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);} 
const escapeHtml=v=>String(v??'').replace(/[&<>'"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[s]));
function getEffectiveStatus(l){return locallyTransitioned.get(l.load_number)||l.checkin_status||'active';}
function getStatusClass(t,s){if(s==='completed'||s==='cancelled')return 'status-gray';if(!t)return 'status-red';const m=(Date.now()-new Date(t).getTime())/6e4;return m<120?'status-green':m<240?'status-amber':'status-red';}
function shouldRenderLoad(l){const s=getEffectiveStatus(l);if(activeFilter==='all')return true;if(activeFilter==='completed'||activeFilter==='cancelled')return s===activeFilter;return s!=='completed'&&s!=='cancelled';}
function renderDashboard(){Object.values(markers).forEach(m=>map.removeLayer(m));markers={};const list=document.getElementById('load-list');list.innerHTML='';dashboardLoads.filter(shouldRenderLoad).forEach(load=>{const sc=getStatusClass(load.last_checkin,getEffectiveStatus(load));const c=document.createElement('div');c.className=`load-card ${sc}`;c.innerHTML=`<div class='card-line1'><span class='card-dot'></span><span class='card-load'>${escapeHtml(load.load_number||'Unassigned')}</span></div><div class='card-line2'><strong>Carrier:</strong> ${escapeHtml(load.carrier_name||'Pending Details')}</div><div class='card-line2'><strong>Driver:</strong> ${escapeHtml(load.driver_name||'Unknown Driver')}</div>`;c.onclick=()=>selectLoad(load);list.appendChild(c);if(load.latest_lat&&load.latest_lng){markers[load.load_number]=L.marker([+load.latest_lat,+load.latest_lng],{icon:truckIcon}).addTo(map);}})}
async function loadDashboardData(){const r=await fetch('v1/admin/map-data.php');const d=await r.json();if(d.success){dashboardLoads=d.loads||[];collectCarrierIndex();renderDashboard();}}
async function drawTrail(loadNumber){clearTrail();const r=await fetch('v1/admin/map-data.php?load_number='+encodeURIComponent(loadNumber));const data=await r.json();if(!data.success||!Array.isArray(data.pings)||data.pings.length<2)return;const latlngs=data.pings.map(p=>[+p.lat,+p.lng]).filter(x=>!Number.isNaN(x[0])&&!Number.isNaN(x[1]));if(latlngs.length<2)return;currentTrailLayer=L.polyline(latlngs,{color:'#00ffcc',weight:4,opacity:.8}).addTo(map);map.fitBounds(currentTrailLayer.getBounds(),{padding:[24,24]});}
function selectLoad(l){if(l.latest_lat&&l.latest_lng)map.setView([+l.latest_lat,+l.latest_lng],10);drawTrail(l.load_number);} function filterByStatus(s,b){activeFilter=s;document.querySelectorAll('.status-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderDashboard();} window.filterByStatus=filterByStatus;
function clearTrail(){if(currentTrailLayer){map.removeLayer(currentTrailLayer);currentTrailLayer=null;}} window.clearTrail=clearTrail;

function showPanel(n){manualPanel=n;document.querySelectorAll('.manual-panel').forEach(el=>el.classList.toggle('hidden',+el.dataset.panel!==n));document.querySelectorAll('.manual-tab').forEach(el=>{const isActive=+el.dataset.panel===n;el.classList.toggle('active',isActive);el.classList.toggle('wizard-step-node',true);});document.getElementById('manual-back-btn').classList.toggle('hidden',n===1);document.getElementById('manual-next-btn').classList.toggle('hidden',n===3);document.getElementById('manual-submit-btn').classList.toggle('hidden',n!==3);} 
function err(msg){document.getElementById('manual-error').textContent=msg||'';}
function addStopRow(stop={milestone:'transit',city:'',state:'',scheduled_at:''}){const w=document.getElementById('stops-wrap');const i=w.children.length;const r=document.createElement('div');r.className='stop-row';r.innerHTML=`<label>Milestone <select name='stop[${i}][milestone]'><option value='pickup'>pickup</option><option value='transit'>transit</option><option value='delivery'>delivery</option></select></label><label>City <input type='text' name='stop[${i}][city]' value='${escapeHtml(stop.city)}' ></label><label>State <input type='text' name='stop[${i}][state]' value='${escapeHtml(stop.state)}'></label><label>Scheduled <input type='datetime-local' name='stop[${i}][scheduled_at]' value='${escapeHtml(stop.scheduled_at)}'></label><button type='button' class='remove-stop'>Remove</button>`;w.appendChild(r);r.querySelector('select').value=stop.milestone;r.querySelector('.remove-stop').onclick=()=>{r.remove();};}
function panelValid(p){if(p===1){return !!document.getElementById('carrier_name').value.trim();}if(p===2){return normalizePhone(document.getElementById('driver_phone').value).length===10;}if(p===3){return !!document.getElementById('load_number').value.trim();}return true;}
async function searchFmcsa(){const q=document.getElementById('carrier_name').value.trim();if(q.length<2){err('Enter at least 2 characters for FMCSA search.');return;}const r=await fetch('v1/admin/fmcsa-search.php?q='+encodeURIComponent(q));const data=await r.json();const box=document.getElementById('carrier-results');box.innerHTML='';(data||[]).forEach(item=>{const row=document.createElement('button');row.type='button';row.className='carrier-result';row.textContent=`${item.legal_name} (${item.dot_number}) ${item.city}, ${item.state}`;row.onclick=()=>{document.getElementById('carrier_id').value='0';document.getElementById('carrier_name').value=item.legal_name||'';document.getElementById('dot_number').value=item.dot_number||'';box.innerHTML='';};box.appendChild(row);});}
async function loadDrivers(){const carrierId=+document.getElementById('carrier_id').value||0;const sel=document.getElementById('driver_select');sel.innerHTML='<option value="0">+ New Driver</option>';if(carrierId<=0)return;const r=await fetch('v1/admin/carrier-drivers.php?carrier_id='+carrierId);const data=await r.json();(data||[]).forEach(d=>{const op=document.createElement('option');op.value=String(d.id);op.textContent=`${d.driver_name} (${d.driver_phone})`;op.dataset.phone=d.driver_phone||'';op.dataset.email=d.driver_email||'';op.dataset.name=d.driver_name||'';sel.appendChild(op);});}

document.addEventListener('DOMContentLoaded',()=>{initMap();loadDashboardData();setInterval(loadDashboardData,8000);
const modal=document.getElementById('addLoadModal');if(!modal)return;
const addBtn=document.getElementById('ADD_LOAD_BTN');if(addBtn){addBtn.onclick=()=>modal.classList.remove('hidden');}

document.getElementById('fmcsa-btn').onclick=searchFmcsa; document.getElementById('manualCarrierEntry').onclick=()=>{document.getElementById('carrier_id').value='0';document.getElementById('carrier-results').innerHTML='';}; document.getElementById('carrier_name').addEventListener('input',(e)=>renderCarrierTypeahead(e.target.value.trim()));
const sel=document.getElementById('driver_select');sel.onchange=()=>{const isNew=sel.value==='0';document.getElementById('driver_id').value=sel.value;document.getElementById('new-driver-form').style.display=isNew?'block':'none';if(!isNew){const op=sel.selectedOptions[0];document.getElementById('driver_name').value=op.dataset.name||'';document.getElementById('driver_phone').value=op.dataset.phone||'';document.getElementById('driver_email').value=op.dataset.email||'';}};
const clearBtn=document.getElementById('manual-clear-btn');if(clearBtn)clearBtn.addEventListener('click',resetManualLoadForm);
showPanel(1);document.getElementById('manual-next-btn').onclick=()=>{if(!panelValid(manualPanel)){if(!document.getElementById('manual-error').textContent)err('Carrier and 10-digit driver phone are required.');return;}err('');if(manualPanel===1)loadDrivers();showPanel(Math.min(3,manualPanel+1));};document.getElementById('manual-back-btn').onclick=()=>showPanel(Math.max(1,manualPanel-1));document.getElementById('manual-close-btn').onclick=()=>{modal.classList.add('hidden');resetManualLoadForm();};document.getElementById('add-stop-btn').onclick=()=>addStopRow();
if(document.querySelectorAll('.stop-row').length===0){addStopRow({milestone:'pickup'});addStopRow({milestone:'delivery'});} 
modal.addEventListener('hidden.bs.modal',resetManualLoadForm);
 document.getElementById('manual-load-form').addEventListener('submit',async e=>{e.preventDefault();if(!panelValid(1)||!panelValid(2)||!panelValid(3)){err('Carrier name, load number, and a 10-digit driver phone are required.');return;}document.querySelectorAll('.stop-row').forEach((row)=>{const city=row.querySelector("input[name*='[city]']");const state=row.querySelector("input[name*='[state]']");if(city && !city.value.trim()) city.value='Pending Details'; if(state && !state.value.trim()) state.value='Pending Details';});const driverName=document.getElementById('driver_name');if(driverName&&!driverName.value.trim())driverName.value='Unknown Driver';const driverEmail=document.getElementById('driver_email');if(driverEmail&&!driverEmail.value.trim())driverEmail.value='Pending Details';const phone=document.getElementById('driver_phone');if(phone)phone.value=normalizePhone(phone.value);const fd=new FormData(e.currentTarget);const res=await fetch('v1/admin/create-load.php',{method:'POST',body:fd});const data=await res.json().catch(()=>({}));if(!res.ok||data.success===false){err(data.message||'Failed to create load');return;}modal.classList.add('hidden');resetManualLoadForm();loadDashboardData();});
});
