// existing map logic retained plus manual wizard system
let map;let markers={};let currentTrailLayer=null;let activeFilter='active';let dashboardLoads=[];const locallyTransitioned=new Map();
let manualPanel=1;const wizardState={carrier_id:0,driver_id:0,stops:[]};
function resetManualLoadForm(){
const form=document.getElementById('manual-load-form');if(!form)return;
form.reset();
wizardState.carrier_id=0;wizardState.driver_id=0;wizardState.stops=[];
['carrier_id','driver_id','selected_carrier_id','selected_driver_id'].forEach(id=>{const el=document.getElementById(id);if(el)el.value='0';});
['carrier_name','dot_number','driver_name','driver_phone','driver_email','load_number'].forEach(id=>{const el=document.getElementById(id);if(el)el.value='';});
const stopsWrap=document.getElementById('stops-wrap');if(stopsWrap){stopsWrap.innerHTML='';addStopRow({milestone:'pickup'});addStopRow({milestone:'delivery'});} 
const results=document.getElementById('carrier-results');if(results)results.innerHTML='';
const sel=document.getElementById('driver_select');if(sel){sel.value='0';['driver_name','driver_phone','driver_email'].forEach(id=>{const lbl=document.getElementById(id)?.closest('label');if(lbl)lbl.style.display='block';});}
err('');showPanel(1);
}
function initMap(){map=L.map('map').setView([43,-93.5],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);} 
const escapeHtml=v=>String(v??'').replace(/[&<>'"]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[s]));
function getEffectiveStatus(l){return locallyTransitioned.get(l.load_number)||l.checkin_status||'active';}
function getStatusClass(t,s){if(s==='completed'||s==='cancelled')return 'status-gray';if(!t)return 'status-red';const m=(Date.now()-new Date(t).getTime())/6e4;return m<120?'status-green':m<240?'status-amber':'status-red';}
function shouldRenderLoad(l){const s=getEffectiveStatus(l);if(activeFilter==='all')return true;if(activeFilter==='completed'||activeFilter==='cancelled')return s===activeFilter;return s!=='completed'&&s!=='cancelled';}
function renderDashboard(){Object.values(markers).forEach(m=>map.removeLayer(m));markers={};const list=document.getElementById('load-list');list.innerHTML='';dashboardLoads.filter(shouldRenderLoad).forEach(load=>{const sc=getStatusClass(load.last_updated_at,getEffectiveStatus(load));const c=document.createElement('div');c.className=`load-card ${sc}`;c.innerHTML=`<div class='card-line1'><span class='card-dot'></span><span class='card-load'>${escapeHtml(load.load_number)}</span></div>`;c.onclick=()=>selectLoad(load);list.appendChild(c);if(load.latest_lat&&load.latest_lng){markers[load.load_number]=L.marker([+load.latest_lat,+load.latest_lng]).addTo(map);}})}
async function loadDashboardData(){const r=await fetch('v1/admin/map-data.php');const d=await r.json();if(d.success){dashboardLoads=d.loads||[];renderDashboard();}}
function selectLoad(l){if(l.latest_lat&&l.latest_lng)map.setView([+l.latest_lat,+l.latest_lng],10);} function filterByStatus(s,b){activeFilter=s;document.querySelectorAll('.status-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderDashboard();} window.filterByStatus=filterByStatus;
function clearTrail(){if(currentTrailLayer){map.removeLayer(currentTrailLayer);currentTrailLayer=null;}} window.clearTrail=clearTrail;

function showPanel(n){manualPanel=n;document.querySelectorAll('.manual-panel').forEach(el=>el.classList.toggle('hidden',+el.dataset.panel!==n));document.querySelectorAll('.manual-tab').forEach(el=>el.classList.toggle('active',+el.dataset.panel===n));document.getElementById('manual-back-btn').classList.toggle('hidden',n===1);document.getElementById('manual-next-btn').classList.toggle('hidden',n===3);document.getElementById('manual-submit-btn').classList.toggle('hidden',n!==3);} 
function err(msg){document.getElementById('manual-error').textContent=msg||'';}
function addStopRow(stop={milestone:'transit',city:'',state:'',scheduled_at:''}){const w=document.getElementById('stops-wrap');const i=w.children.length;const r=document.createElement('div');r.className='stop-row';r.innerHTML=`<label>Milestone <select name='stop[${i}][milestone]'><option value='pickup'>pickup</option><option value='transit'>transit</option><option value='delivery'>delivery</option></select></label><label>City <input type='text' name='stop[${i}][city]' value='${escapeHtml(stop.city)}' required></label><label>State <input type='text' name='stop[${i}][state]' value='${escapeHtml(stop.state)}' required></label><label>Scheduled <input type='datetime-local' name='stop[${i}][scheduled_at]' value='${escapeHtml(stop.scheduled_at)}'></label><button type='button' class='remove-stop'>Remove</button>`;w.appendChild(r);r.querySelector('select').value=stop.milestone;r.querySelector('.remove-stop').onclick=()=>{r.remove();};}
function panelValid(p){if(p===1){return !!document.getElementById('carrier_name').value.trim();}if(p===2){const phone=document.getElementById('driver_phone').value.trim();return /^\+[1-9]\d{1,14}$/.test(phone)&&!!document.getElementById('driver_name').value.trim();}if(p===3){const stops=[...document.querySelectorAll('.stop-row')];if(stops.length<2){err('At least 2 stops are required.');return false;}const deliveries=[...document.querySelectorAll("select[name*='[milestone]']")].filter(x=>x.value==='delivery').length;if(deliveries!==1){err('Exactly one delivery stop is required.');return false;}return !!document.getElementById('load_number').value.trim();}return true;}
async function searchFmcsa(){const q=document.getElementById('carrier_name').value.trim();if(q.length<2){err('Enter at least 2 characters for FMCSA search.');return;}const r=await fetch('v1/admin/fmcsa-search.php?q='+encodeURIComponent(q));const data=await r.json();const box=document.getElementById('carrier-results');box.innerHTML='';(data||[]).forEach(item=>{const row=document.createElement('button');row.type='button';row.className='carrier-result';row.textContent=`${item.legal_name} (${item.dot_number}) ${item.city}, ${item.state}`;row.onclick=()=>{document.getElementById('carrier_id').value='0';document.getElementById('carrier_name').value=item.legal_name||'';document.getElementById('dot_number').value=item.dot_number||'';box.innerHTML='';};box.appendChild(row);});}
async function loadDrivers(){const carrierId=+document.getElementById('carrier_id').value||0;const sel=document.getElementById('driver_select');sel.innerHTML='<option value="0">+ New Driver</option>';if(carrierId<=0)return;const r=await fetch('v1/admin/carrier-drivers.php?carrier_id='+carrierId);const data=await r.json();(data||[]).forEach(d=>{const op=document.createElement('option');op.value=String(d.id);op.textContent=`${d.driver_name} (${d.driver_phone})`;op.dataset.phone=d.driver_phone||'';op.dataset.email=d.driver_email||'';op.dataset.name=d.driver_name||'';sel.appendChild(op);});}

document.addEventListener('DOMContentLoaded',()=>{initMap();loadDashboardData();setInterval(loadDashboardData,8000);
const modal=document.getElementById('addLoadModal');if(!modal)return;
const addBtn=document.getElementById('ADD_LOAD_BTN');if(addBtn){addBtn.onclick=()=>modal.classList.remove('hidden');}

const p1=document.querySelector(".manual-panel[data-panel='1']");if(!document.getElementById('carrier-results')){const d=document.createElement('div');d.id='carrier-results';p1.appendChild(d);const b=document.createElement('button');b.type='button';b.id='fmcsa-btn';b.textContent='Search FMCSA';p1.appendChild(b);b.onclick=searchFmcsa;}
const p2=document.querySelector(".manual-panel[data-panel='2']");if(!document.getElementById('driver_select')){const sel=document.createElement('select');sel.id='driver_select';sel.innerHTML='<option value="0">+ New Driver</option>';p2.prepend(sel);sel.onchange=()=>{const isNew=sel.value==='0';document.getElementById('driver_id').value=sel.value;['driver_name','driver_phone','driver_email'].forEach(id=>document.getElementById(id).closest('label').style.display=isNew?'block':'none');if(!isNew){const op=sel.selectedOptions[0];document.getElementById('driver_name').value=op.dataset.name||'';document.getElementById('driver_phone').value=op.dataset.phone||'';document.getElementById('driver_email').value=op.dataset.email||'';}};}
const actions=document.querySelector('#manual-load-form .manual-actions');if(actions&&!document.getElementById('manual-clear-btn')){const clearBtn=document.createElement('button');clearBtn.type='button';clearBtn.id='manual-clear-btn';clearBtn.className='btn-clear-form';clearBtn.textContent='Clear Form';actions.prepend(clearBtn);clearBtn.addEventListener('click',resetManualLoadForm);} 
showPanel(1);document.getElementById('manual-next-btn').onclick=()=>{if(!panelValid(manualPanel)){if(!document.getElementById('manual-error').textContent)err('Please complete required fields before continuing.');return;}err('');if(manualPanel===1)loadDrivers();showPanel(Math.min(3,manualPanel+1));};document.getElementById('manual-back-btn').onclick=()=>showPanel(Math.max(1,manualPanel-1));document.getElementById('manual-close-btn').onclick=()=>modal.classList.add('hidden');document.getElementById('add-stop-btn').onclick=()=>addStopRow();
if(document.querySelectorAll('.stop-row').length===0){addStopRow({milestone:'pickup'});addStopRow({milestone:'delivery'});} 
 modal.addEventListener('hidden.bs.modal',resetManualLoadForm);
 document.getElementById('manual-load-form').addEventListener('submit',async e=>{e.preventDefault();if(!panelValid(3))return;const fd=new FormData(e.currentTarget);const res=await fetch('v1/admin/create-load.php',{method:'POST',body:fd});const data=await res.json().catch(()=>({}));if(!res.ok||data.success===false){err(data.message||'Failed to create load');return;}modal.classList.add('hidden');resetManualLoadForm();loadDashboardData();});
});
